name: Arduino Lint

on:
  push:
    paths:
      - ".github/workflows/main.yml"
      - "src/**"
      - "library.properties"
  pull_request:
    paths:
      - ".github/workflows/main.yml"
      - "src/**"
      - "library.properties"

jobs:
  lint:
    name: Arduino Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Run Arduino Lint
        uses: arduino/arduino-lint-action@v1
        with:
          library-manager: update
          compliance: strict